### ISSUE TITLE
小米5 Android7.0下运行 发生了闪退

### ISSUE THREAD

**Issue by pengzee** [liuzho/ONE#3]
04-13 16:02:14.183 6078-6078/com.liuzh.one E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.liuzh.one, PID: 6078
                                                             java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 672936 free bytes and 657KB until OOM
                                                                 at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                 at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                 at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:624)
                                                                 at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:457)
                                                                 at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1152)
                                                                 at android.content.res.ResourcesImpl.createFromResourceStream(ResourcesImpl.java:1272)
                                                                 at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:743)
                                                                 at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:585)
                                                                 at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:305)
                                                                 at android.content.res.Resources.loadDrawable(Resources.java:872)
                                                                 at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
                                                                 at android.graphics.drawable.AnimationDrawable.inflateChildElements(AnimationDrawable.java:327)
                                                                 at android.graphics.drawable.AnimationDrawable.inflate(AnimationDrawable.java:297)
                                                                 at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
                                                                 at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1226)
                                                                 at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1199)
                                                                 at android.content.res.ResourcesImpl.createFromXml(ResourcesImpl.java:1284)
                                                                 at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:735)
                                                                 at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:585)
                                                                 at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:305)
                                                                 at android.content.res.Resources.loadDrawable(Resources.java:872)
                                                                 at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
                                                                 at android.widget.ImageView.<init>(ImageView.java:157)
                                                                 at android.widget.ImageView.<init>(ImageView.java:145)
                                                                 at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
                                                                 at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
                                                                 at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
                                                                 at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
                                                                 at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
                                                                 at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:989)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:879)
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                 at com.liuzh.one.activity.BaseActivity.onCreate(BaseActivity.java:27)
                                                                 at android.app.Activity.performCreate(Activity.java:6736)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2722)
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6114)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
04-13 16:02:14.184 6078-6078/com.liuzh.one E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
04-13 16:02:14.680 472-2743/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
                                                        return value 2

**Comment by liuzho** [comment]
图片加载都用的Picasso呀应该不会OOM，我在7.0的模拟器上暂时没出现OOM，手上也没mi5可以测试/(ㄒoㄒ)/。。。抱歉暂时没法处理。。

**Comment by pengzee** [comment]
确实有闪退，建议你好好查查。。。

**Comment by liuzho** [comment]
可是....我手上没有米5    T_T，我自用暂时没有发生闪退呀，我相信你说的问题存在，可是我现在真的没法解决，问题没法复现。。。。
